### ISSUE TITLE
Complete HTML/CSS mock: Workspace

### ISSUE THREAD

**Issue by gwynethsc** [googleinterns/step71-2020#4]

**Comment by Google-JM** [comment]
Status update:
 - Looking into adjustable panels for horizontal workspace split.
 - Looking the lyric editing or using a google doc.

**Comment by gwynethsc** [comment]
Status Update:
 - Looking into waveforms
 - Looking into taking different audio files into account (convert to WAV file?)
    - could separate into MVP/stretch goals
