### ISSUE TITLE
Complete HTML/CSS mock: Chat Integration

### ISSUE THREAD

**Issue by gwynethsc** [googleinterns/step71-2020#7]
This module will likely want to be visible/accessible from most, if not all, pages, and priority/pinned content may vary with context

e.g. 
When in project overview, all top-level project chats are visible
When in a specific project or workspace, project-specific or file-specific chat channels float to the top
When in profile/discovery contexts, private chats not tied to projects are at the top

on the other hand, this schema may be too complicated/confusing for users as well

**Comment by Google-JM** [comment]
Status Update:
- Will start working on after Project overview.

**Comment by gwynethsc** [comment]
Status Update:
 - Has empty placeholder drawer component
